version: "3"

services:
  easytask:
    image: zhouxin98/easytask:latest
    container_name: easytask
    ports:
      - "3001:3001"
      - "3000:3000"
    volumes:
      - /path/to/scripts:/app/server/scripts
    environment:
      - PORT=3001
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    restart: unless-stopped