version: "3"

services:
  easytask:
    image: zhouxin98/easytask:latest
    container_name: easytask
    ports:
      - "80:80"
      - "3001:3001"
    volumes:
      - /path/to/scripts:/app/server/scripts
    environment:
      - PORT=3001
      - VITE_HOST=0.0.0.0
    restart: unless-stopped